[package]
name = "bikeshed2"
version = "4.1.6"
edition = "2021"

[[bin]]
name = "bikeshed"
path = "src/main.rs"

[build-dependencies]
tar = "0.4.40"
zip = "1.3.0"
flate2 = "1.0.30"
xdg = "2.5.2"

[dependencies]
tar = "0.4.40"
zip = "1.3.0"
flate2 = "1.0.30"
xdg = "2.5.2"
