[package]
name = "bikeshed"
version = "4.1.61"
edition = "2021"

[build-dependencies]
tar = "0.4.40"
zip = "1.2.1"
flate2 = "1.0.30"
xdg = "2.5.2"
build-target = "0.4.0"

[dependencies]
xdg = "2.5.2"
exec = "0.3.1"
zip-extract = "0.1.3"
build-target = "0.4.0"
