name: cargo build
on:
  push:
    branches: ["main"]
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/cargo-build.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/cargo-build.yml"
  workflow_call:
concurrency:
  group: cargo-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cargo-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Use older Ubuntu distro to force older glibc
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: arm64-apple-darwin
          - os: macos-13
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test --locked
      - run: cargo build --target "$TARGET" --release --locked
        env:
          TARGET: ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: bikeshed-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/bikeshed